### PR TITLE
New component analysis smoke tests

### PR DESCRIPTION
**Pull request by tisnik**

### CODE REVIEW

**Comment by tisnik** [comment]
Yup @yzainee we are going to add more packages. OTOH it's always good to check the logic with different versions of the same component as well.

**Comment by tisnik** [comment]
@yzainee ok to merge or do we need to add more components?

**Comment by yzainee** [comment]
I think its ok to merge now.. as long as we keep a track of this and keep adding more components

**Comment by tisnik** [comment]
@yzainee yes, Yusuf, then I need to ack :)

**Pull request merged**
