### PR TITLE
1st version of smoke test

### PR DESCRIPTION
**Pull request by tisnik**
Let's start working on more integration  tests. This is the very first and very simple version for smoke test. At least it allow us not to start just the fake 'disabled' test.

### CODE REVIEW

**Comment by jpopelka** [comment]
Pavel, I can see a 'Merge branch ... ' commit in the commit history now.
This can be easily avoided, the trick is in 'rebasing' branches rather than 'merging'.

See for example these links for the theory:
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

I'm not sure how your workflow looks like, but here are examples what to
change to 'fix' it:

* do `git pull --rebase` instead of `git pull`
* do `git rebase` instead of `git merge`

The 'rebasing' changes history so you might need to do `git push -f`
instead of `git push` after 'rebasing'.

**Comment by tisnik** [comment]
Thanks @jpopelka . Is it possible to fix it right now (w/o reseting or so) or is it better to just create new PR?

**Comment by jpopelka** [comment]
Sure, try:

1. git rebase master
2. git push -f

**Comment by tisnik** [comment]
Thanks @jpopelka . Yeah the push -f is what I meant (some form of history reset;)

**Comment by tisnik** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
LGTM, thanks 😉

**Pull request merged**
