### PR TITLE
Use PUT method to logout

### PR DESCRIPTION
**Pull request by tisnik**
I'd suggest to merge this change when https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/134 will be deployed to Stage. (now the test failed on CI, it is to be expected)

### CODE REVIEW

**Comment by fridex** [comment]
[test this]

**Comment by fridex** [comment]
[test this]

**Comment by fridex** [comment]
This should be already done: https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/integration-tests/features/steps/common.py#L541 - PR https://github.com/fabric8-analytics/fabric8-analytics-common/pull/264

@tisnik, are we OK with closing this?

**Comment by tisnik** [comment]
@fridex yes, definitely.

**Pull request closed without merging**
