### PR TITLE
Changes stack analyses scenario tests for new schema

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**
Here is the latest stack analyses response for the ready reference of the reviewer - https://gist.github.com/samuzzal-choudhury/7a21f8da317b1771c5973e9b9faf0d7a

The current error during the integration tests is -

```
      Traceback (most recent call last):
        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/lib/python3.4/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "/tests/features/steps/stack_analysis.py", line 318, in stack_analysis_check_companion_packages
          analyzed_packages = get_analyzed_packages(json_data)
        File "/tests/features/steps/stack_analysis.py", line 302, in get_analyzed_packages
          return get_attribute_values(analyzed_packages, "package")
        File "/tests/features/steps/stack_analysis.py", line 295, in get_attribute_values
          return [item[attribute_name] for item in list]
        File "/tests/features/steps/stack_analysis.py", line 295, in <listcomp>
          return [item[attribute_name] for item in list]
      KeyError: 'package'
```

### CODE REVIEW

**Comment by tisnik** [comment]
It looks good to me @samuzzal-choudhury, but because the tests are run against the Stage, we see the test failures.

**Comment by msrb** [comment]
The latest worker is available in staging, let's test this again.

**Comment by msrb** [comment]
[test this]

**Comment by fridex** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
LGTM, thanks everyone for fixing tests :)

**Comment by msrb** [comment]
Green!

Thanks @tisnik and @samuzzal-choudhury 😉

**Pull request merged**
