### PR TITLE
Corrected a test to validate stacks-report endpoint

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**

### CODE REVIEW

**Comment by tisnik** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
@samuzzal-choudhury please merge as all CI jobs passed

**Comment by samuzzal-choudhury** [comment]
@tisnik merging this as all the tests have passed.

**Pull request merged**
