### PR TITLE
e2e fixes

### PR DESCRIPTION
**Pull request by sawood14012**
# Description

just an small e2e fix

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by yzainee — APPROVED** [review]
check has failed

**Comment by yzainee** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Comment by yzainee** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Pull request merged**
