### PR TITLE
disable api feature tests till we fix schema

### PR DESCRIPTION
**Pull request by miteshvp**

### CODE REVIEW

**Comment by tisnik** [comment]
@miteshvp do we have ETA to enable those tests?

**Comment by miteshvp** [comment]
@tisnik - ideally we should remove those schema checks for removal of workers as well.
cc @msrb @msehnout - Can you please give some ETA here?

**Comment by miteshvp** [comment]
@msrb @msehnout - any updates here? Can we enable these tests now?

**Comment by msehnout** [comment]
The code was removed from workers. As far as I know the work should be finished there.

**Pull request merged**
