### PR TITLE
Fix NLTK and Pandas versions

### PR DESCRIPTION
**Pull request by tisnik**

### CODE REVIEW

**Comment by miteshvp** [comment]
@tisnik - I guess we need to rethink on these test cases. Because with every new release of a library used in our testing, our E2E tests will fail with the same error. WDYT?

**Comment by tisnik** [comment]
@miteshvp I'd rather have these checks part of proper setup unit tests, because it makes more sense and unit tests use more controllable environment

**Comment by miteshvp** [comment]
I agree tests are more fragile as you move up, but these tests can never be part of unit tests since we have more than one service that is needed in order to validate a package recommended with version. Hence, it has to be part of integrations tests.

**Comment by animuk** [comment]
@tisnik agree with mitesh. Introducing these use cases in the integration test, affects the stability of our e2e master build.

**Comment by tisnik** [comment]
that's definitely two-sided sword. Do we want to have "just" e2e tests or do we wanna to test thje API thoroughly through them? In the second case, there's an inherent fragility.

**Comment by tisnik** [comment]
@miteshvp as these tests needs manual checks + fixes anyway, I'm ok to keep them as is. Let's discuss it on cabal.

**Pull request merged**
