### PR TITLE
pausing e2e

### PR DESCRIPTION
**Pull request by deepak1725**
# Description

Pausing Dynamic Manifests E2E. E2E Failing Because of this scnerio. Pausing this for Debugging and unblocking other PR's.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by tisnik** [comment]
Why it is needed to be done this way? Far better approach would be to use proper tag and don't run tests with such tag on stage.

**Comment by miteshvp** [comment]
@tisnik - use of tag requires to modify opensifhit-cico-job script everytime you need to disable certain tests. 
@deepak1725 - please create a new feature file and then we can enable/disable using feature_list.txt file

**Comment by miteshvp** [comment]
Merging it to unblock other E2E tests

**Comment by tisnik** [comment]
@miteshvp there's @data-sanity tag that's disabled on stage already

**Pull request merged**
