### PR TITLE
Add secrets template

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Up-to-date template for secrets.

**Comment by msrb** [comment]
@tuxdna PTAL :)

**Comment by tuxdna** [comment]
What is the other template for? https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/openshift/cloud-deploy/secrets-template-aws.yaml

**Comment by tuxdna** [comment]
LGTM, otherwise. We can merge.

**Comment by msrb** [comment]
@tuxdna 

> What is the other template for? https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/openshift/cloud-deploy/secrets-template-aws.yaml

could-deployer should produce secrets in that format (I haven't tested it though).

The purpose of this new file:
We can point SD team to this new file and ask them to add missing secrets to prod.

**Comment by tuxdna** [comment]
@msrb Let me take a moment to understand what that template ( from cloud-deploy ) is used for.

**Comment by tuxdna** [comment]
Alright, the other template looks old, and doesn't seem relevant for now. We can merge this PR.

**Comment by tuxdna** [comment]
[test this]

**Pull request merged**
