### PR TITLE
Chore: Extend User Management Tests Support for SA and CA [APPAI - 1486]

### PR DESCRIPTION
**Pull request by sawood14012**
# Description
This Specific PR deals with adding of new tests that will extend for Registered Users e2e flow for stack analysis and component analysis.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Review by prashbnair — APPROVED** [review]

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Comment by sawood14012** [comment]
[test]

**Pull request merged**
