### PR TITLE
Revert "Revert "Revert "Disable all jobs tests for now"""

### PR DESCRIPTION
**Pull request by fridex**
Reverts fabric8-analytics/fabric8-analytics-common#81

### CODE REVIEW

**Comment by fridex** [comment]
Related: https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/82#issuecomment-310988222

**Comment by pkajaba** [comment]
[test this]

**Comment by pkajaba** [comment]
This should work now. If CI passes, I will merge.

**Comment by fridex** [comment]
> @fridex is it really WIP?

Feel free to do it :)

**Comment by pkajaba** [comment]
Thanks for the confirmation!

**Pull request merged**
