### PR TITLE
Pom xml script more examples + helper script to transform + source data

### PR DESCRIPTION
**Pull request by tisnik**

### CODE REVIEW

**Comment by fridex** [comment]
[test this]

**Comment by fridex** [comment]
AFAICS changes shouldn't affect CI results, but let's give it a try... :)

**Comment by tisnik** [comment]
@fridex the failure is AFAIK caused by a full filesystem on a slave (I've seen this error message several times before ;)

**Comment by fridex** [comment]
> @fridex the failure is AFAIK caused by a full filesystem on a slave (I've seen this error message several times before ;)

Ah, haven't checked the error message - merging anyway as this will not affect CI, slaves get cleaned automatically...

**Pull request merged**
