### PR TITLE
Reflect changes in stack analysis v2 API

### PR DESCRIPTION
**Pull request by tisnik**
Update needed by change in stack analysis v2 API mentioned here:
https://github.com/openshiftio/openshift.io/issues/378

### CODE REVIEW

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Pull request merged**
