### PR TITLE
Test step to check outlier probability

### PR DESCRIPTION
**Pull request by tisnik**
Special test step for checking outlier probability in the generated stack analysis v2.

### CODE REVIEW

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
[test this]

**Comment by tisnik** [comment]
@fridex, sorry to disturb you, but WDYT^?

**Comment by fridex** [comment]
> @fridex, sorry to disturb you, but WDYT^?

No disturbtion noted. 😉

**Comment by samuzzal-choudhury** [comment]
@fridex Took the liberty to merge this PR :-)

**Pull request merged**
