### PR TITLE
[jenkins] Inject API token as environment variable

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
let's see if this gets us further...

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
Ok, and now CI should be green. Let's see...

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
And we are green ladies and gentlemen :)

**Comment by tisnik** [comment]
Awesome, thank you @msrb

**Pull request merged**
