### PR TITLE
Change in status code for a 3scale test.

### PR DESCRIPTION
**Pull request by GeetikaBatra**
This change is in accordance to the change of status code in 3scale-connect-api.
reference:-
https://github.com/fabric8-analytics/f8a-3scale-connect-api/pull/22

### CODE REVIEW

**Comment by tisnik** [comment]
LGTM, thanks a lot @GeetikaBatra

**Comment by GeetikaBatra** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by GeetikaBatra** [comment]
[test]

**Comment by GeetikaBatra** [comment]
@tisnik, I think we need to merge this one, as tests would never pass for this one. The e2e in pipeline, currently check for 400 status, which is right now changed to 404.

**Comment by GeetikaBatra** [comment]
Thanks @tisnik 👍

**Comment by GeetikaBatra** [comment]
[test]

**Pull request merged**
