### PR TITLE
Run database migrations in docker-compose

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
[test this]

**Comment by fridex** [comment]
Or maybe we should change worker-db-migrations instead (more clear and also has alembic migrations mounted as a volume). CC @msrb

**Comment by fridex** [comment]
self-merging as this is critical fix for deployment

**Comment by msrb** [comment]
Not sure what you mean by "change worker-db-migrations instead"?

**Comment by fridex** [comment]
> Not sure what you mean by "change worker-db-migrations instead"?

Not relevant anymore. I've turned on migrations in the api worker first as it is done in the deployment. worker-db-migrations is better fit for sure for now. Sorry for confusion :)

**Pull request merged**
