### PR TITLE
Remove anitya from integration tests, local development and devcluster deployment

### PR DESCRIPTION
**Pull request by pkajaba**

### CODE REVIEW

**Comment by jpopelka** [comment]
Since you're [removing](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/491) all 'downstream' related code, check also  [this](https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/integration-tests/features/steps/s3_component_analysis.py#L274), [this](https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/openshift/secrets-template.yaml#L75) and [this](https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/integration-tests/data/clojure_py_core_data/0.2.4/redhat_downstream.json)

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
I know it is still WIP, but the test part LGTM. Thanks a lot!

**Comment by pkajaba** [comment]
I have no clue why did it fail. [test]

**Comment by tisnik** [comment]
Good work, thank you!

**Comment by pkajaba** [comment]
[test]

**Pull request merged**
